name: RAGSearch
channels:
- conda-forge
dependencies:
- python
- sentence_transformers
- faiss-cpu
- numpy
- pandas
- pyodbc
- ipykernel
- requests
- ipywidgets
- requests
- scikit-learn
- streamlit
- matplotlib_scalebar
- plotly